#!/usr/bin/env python

from gadb_clientP import harvest_send
from numpy.random import *

data={}
data['str']='PY'
data['int']=5
data['swt']=5
data['flt']=5.8
data['dbl']=5.5
data['bol']=True
data['+ctrl']=0.6
data['_tag']=''

for k in range(100):
    #data['+ctrl'+str(k)]=randn()
    data['dbl']=randn()
    data['flt']=randn()*10
    harvest_send(data,'test_omfit?3',host='localhost',verbose=True)
