  EXTERNAL init_harvest, harvest_send, set_harvest_payload_nam, &
    & set_harvest_payload_dbl_array, set_harvest_payload_flt_array, &
    & set_harvest_payload_bol, set_harvest_payload_dbl, &
    & set_harvest_payload_flt, set_harvest_payload_swt, &
    & set_harvest_payload_int, set_harvest_payload_str, &
    & set_harvest_verbose, set_harvest_host, set_harvest_protocol, &
    & set_harvest_port, set_harvest_payload_int_array, &
    & get_harvest_tag, set_harvest_tag
  INTEGER :: init_harvest, harvest_send, set_harvest_payload_nam, &
    & set_harvest_payload_dbl_array, set_harvest_payload_flt_array, &
    & set_harvest_payload_bol, set_harvest_payload_dbl, &
    & set_harvest_payload_flt, set_harvest_payload_swt, &
    & set_harvest_payload_int, set_harvest_payload_str, &
    & set_harvest_verbose, set_harvest_host, set_harvest_protocol, &
    & set_harvest_port, set_harvest_payload_int_array, &
    & get_harvest_tag, set_harvest_tag
